name: Doxygen

on:
  pull_request:
    paths:
    - 'src/include/*.h'

jobs:

  Doxygen:
    name: Run doxygen
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.4
    - name: Run check
      run: ./ci/copy_doxygen_files.sh
